[FEATURE] Crafting GUI
Negative-Games/Framework pull request #126
Opened 2022-06-28 08:36 UTC by seailz

[contributing]: https://github.com/Negative-Games/Framework/blob/main/CONTRIBUTING.md

## Pull Request Etiquette

 

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

 

### Changes

- [x] Internal code
- [x] Library interface (affecting end-user code)
- [x] Documentation
- [ ] Other: \_____ 

 

Closes Issue: #99 

## Description

Added a crafting GUI

## Documentation
```java
public class ExampleCraftingGUI extends CraftingGUI {
    public ExampleCraftingGUI() {
        super("&6&lExample Crafting GUI");

        ItemStack diamond = new ItemStack(Material.DIAMOND);
        ItemStack iron = new ItemStack(Material.IRON_INGOT);
        ItemStack gold = new ItemStack(Material.GOLD_INGOT);
        ItemStack bedrock = new ItemStack(Material.BEDROCK);

        // Set an item without a click event
        // The reason why this is a function is because you could do conditional items.
        setItem(0, player -> {
            if (player.hasPermission("myserver.admin")) {
                return bedrock;
            } else {
                return diamond;
            }
        });

        // This is what you would do if you do not want conditional items.
        setItem(0, player -> diamond);

        // Set an item with a click event
        setItemClickEvent(1, player -> diamond, (player, event) -> {
            player.sendMessage("&aYou clicked the diamond!");
            player.closeInventory();
        });

        // Add an item to the next available slot without a click event
        addItem(player -> iron);

        // Add an item to the next available slot with a click event
        addItemClickEvent(player -> gold, (player, event) -> {
            player.sendMessage("&aYou clicked the gold!");
            player.closeInventory();
        });
    }
}
```

2022-06-28 08:45 UTC, seailz commented
ok that's enough attending to issues for today hehe

2022-06-28 09:11 UTC, joeecodes commented
Won't be merged but will be reviewed.

2022-06-29 08:51 UTC, joeecodes requested changes
That's all i've got for now. @NegativeDev any thing to add?

2022-06-29 08:51 UTC, joeecodes commented on src/main/java/games/negative/framework/gui/CraftingGUI.java
> + * @author Negative - modified by Seailz
leave the original author tag as it is. you don't need to add "modified". 

author the code that you write

2022-06-30 08:31 UTC, joeecodes requested changes

2022-06-30 08:31 UTC, joeecodes commented on src/main/java/games/negative/framework/gui/holder/CraftingGUIHolder.java
> + * @author Negative - modified by Seailz
Author notes need to be done in all classes

2022-06-30 08:31 UTC, joeecodes commented on src/main/java/games/negative/framework/gui/listener/GUIListener.java
> +            CraftingGUIHolder base = (CraftingGUIHolder) holder;
Try not to use single word vars, makes it hard to know what it is when referencing it. 

Keep it relevant to what the object it is for

2022-06-30 13:11 UTC, seailz commented on src/main/java/games/negative/framework/gui/listener/GUIListener.java
> +            CraftingGUIHolder base = (CraftingGUIHolder) holder;
Literally the same code from above with a few things tweaked?

2022-07-05 23:36 UTC, joeecodes commented
Are there any screenshots of this being used?

2022-07-06 00:30 UTC, seailz commented
> Are there any screenshots of this being used? Just so I can see what it actually looks like in production.

Will send a few in a couple hours

2022-07-06 00:31 UTC, seailz commented
> Are there any screenshots of this being used? Just so I can see what it actually looks like in production.

there's one on the issue relating to this pr, but that's not created with this framework

2022-07-06 00:31 UTC, seailz commented
> Are there any screenshots of this being used? Just so I can see what it actually looks like in production.

there's one on the issue relating to this pr, but that's not created with this framework

2022-07-06 08:54 UTC, joeecodes commented
> > Are there any screenshots of this being used? Just so I can see what it actually looks like in production.
> 
> there's one on the issue relating to this pr, but that's not created with this framework

is it a thing that needs to be addressed by negative games or not?

2022-07-08 16:03 UTC, seailz commented
> > > Are there any screenshots of this being used? Just so I can see what it actually looks like in production.
> > 
> > 
> > there's one on the issue relating to this pr, but that's not created with this framework
> 
> is it a thing that needs to be addressed by negative games or not?

wdym

2022-07-08 16:07 UTC, joeecodes commented
> > > > Are there any screenshots of this being used? Just so I can see what it actually looks like in production.
> > > 
> > > 
> > > there's one on the issue relating to this pr, but that's not created with this framework
> > 
> > 
> > is it a thing that needs to be addressed by negative games or not?
> 
> wdym

You said theres an issue with this PR. Is it something that needs to be fixed by us?

2022-07-08 16:40 UTC, joeecodes commented
ahhh

2022-10-03 16:10 UTC, closed without merging