[FEATURE] Sign GUI
Negative-Games/Framework pull request #129
Opened 2022-07-02 10:00 UTC by seailz

[contributing]: https://github.com/Negative-Games/Framework/blob/main/CONTRIBUTING.md

## Pull Request Etiquette

 

- [ ] I have checked the PRs for upcoming features/bug fixes.
- [ ] I have read the [contributing guidelines][contributing].

 

### Changes

- [ ] Internal code
- [ ] Library interface (affecting end-user code)
- [ ] Documentation
- [ ] Other: \_____ 

 

Closes Issue: NaN

## Description

Adds a Sign GUI

## Documentation
```java
import games.negative.framework.gui.sign.SignGUI;

public class SignGUITest extends SignGUI {

    public SignGUITest() {
        setLine(1, player -> "---------");
        setLine(2, player -> "Enter some epic text above!");
        setLine(3, player -> "(this is cool)");

        onClose((player, lines) -> {
            System.out.println("Player " + player.getName() + " closed the sign GUI.");
            System.out.println("The lines were: ");
            for (String line : lines) {
                System.out.println(line);
            }
        });

    };
}
```

2022-07-02 12:16 UTC, NegativeDev commented
Has this been tested?

2022-07-02 12:33 UTC, NegativeDev requested changes

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignGUI.java
> + * Custom SignGUI inputs
```suggestion
 * Sign GUI
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignGUI.java
> +     * Opens the sign GUI
```suggestion
     * Opens the menu
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignGUI.java
> +    public void open(Player player) throws ProtocolLibNotInstalledException {
```suggestion
    public void open(@NotNull Player player) throws ProtocolLibNotInstalledException {
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignManager.java
> +    public static void open(Player player, SignGUI signGUI) {
```suggestion
    public static void open(@NotNull Player player, @NotNull SignGUI signGUI) {
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignManager.java
> +        player.sendBlockChange(new Location(player.getWorld(), 0, 0, 0), Material.SIGN, (byte) 0);
This part of the code would only work in 1.8 and below, please consider cross-version compatibility.

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignManager.java
> +        nbt.put("id", "minecraft:sign");
This part of the code would only work in 1.8 and below, please consider cross-version compatibility.

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignManager.java
> +    private static void sendPacket(Player player, PacketContainer packet) {
```suggestion
    private static void sendPacket(@NotNull Player player, @NotNull PacketContainer packet) {
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/packets/SignEditorPacket.java
> +    public SignEditorPacket(PacketContainer packet) {
```suggestion
    public SignEditorPacket(@NotNull PacketContainer packet) {
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/packets/SignEditorPacket.java
> +    public void setLocation(BlockPosition value) {
```suggestion
    public void setLocation(@NotNull BlockPosition value) {
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/packets/general/AbstractPacket.java
> +            throw new IllegalArgumentException("Packet handle cannot be NULL.");
```suggestion
    protected AbstractPacket(@NotNull PacketContainer handle, @NotNull PacketType type) {
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/packets/general/AbstractPacket.java
> +    public void sendPacket(Player receiver) {
```suggestion
    public void sendPacket(@NotNull Player receiver) {
```

2022-07-02 12:33 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/packets/general/AbstractPacket.java
> +    }
Why does this need to be here?

2022-07-02 15:08 UTC, seailz commented on src/main/java/games/negative/framework/gui/sign/packets/general/AbstractPacket.java
> +    }
This is from a packet wrapper repository, will remove

2022-07-02 15:12 UTC, seailz commented on src/main/java/games/negative/framework/gui/sign/SignManager.java
> +        player.sendBlockChange(new Location(player.getWorld(), 0, 0, 0), Material.SIGN, (byte) 0);
not sure how I'm supposed to do this? Material#getValue?

2022-07-02 16:38 UTC, seailz commented
## TODO:
- [ ] Newer Version Support
- [ ] Newer Version Testing
- [ ] Fix Default Lines

2022-07-02 17:12 UTC, NegativeDev requested changes

2022-07-02 17:12 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignManager.java
> +        VersionChecker versionChecker = new VersionChecker();
We already have a VersionChecker instance initialized, please do not initialize a new one. Please use 
```
VersionChecker.getInstance()
```

2022-07-02 17:12 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignManager.java
> +            player.sendBlockChange(new Location(player.getWorld(), 0, 0, 0), Material.valueOf("OAK_SIGN"), (byte) 0);
```suggestion
player.sendBlockChange(new Location(player.getWorld(), 0, 0, 0, versionChecker.isLegacy() ? Material.SIGN : Material.valueOf("OAK_SIGN"), (byte) 0));
```

2022-07-02 17:12 UTC, NegativeDev commented on src/main/java/games/negative/framework/gui/sign/SignManager.java
> +        signDataPacket.getBlockPositionModifier().write(0, location);
```suggestion
        String itemName = versionChecker.isLegacy() ? "minecraft:sign" : "minecraft:oak_sign";
```

2022-10-03 16:10 UTC, closed without merging

2022-10-06 13:40 UTC, seailz commented
@ericlmao can this stay open? I'm gonna start trying to work on it again

2022-10-06 13:43 UTC, seailz commented
> I'm gonna say no, I'll probably make my own implementation of it

bruh moment

2022-10-06 13:45 UTC, seailz commented
let me do some testing with this, I think it may be working